spring:
<<<<<<< HEAD
  profiles:
    active: local
  session:
    store-type: redis
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local
=======
>>>>>>> feat#119
  data:
    redis:
      host: localhost
      port: 6379
<<<<<<< HEAD
logging:
  level:
    org.hibernate.SQL: debug

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: redis
      port: 6379
logging:
  level:
    org.hibernate.SQL: debug
=======

redis:
  item:
    prefix:
      "tickets:"
>>>>>>> feat#119
