spring:
  profiles:
    active: local
  session:
    store-type: redis
server:
  port: 8081
wait:
  queue:
    pass-chunk-size: 150
---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.hibernate.SQL: debug

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: redis
      port: 6379
logging:
  level:
    org.hibernate.SQL: debug
