global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['spring-app:8080']
        labels:
          application: festival
  - job_name: linux_mysql
    static_configs:
      - targets: ['mysql:9100']
  - job_name: mysql_mysql
    static_configs:
      - targets: ['mysql:9104']
  - job_name: redis-exporter
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          application: redis
